name: "setuptools"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12, 3.13]

    steps:
    - name: Initialize pythom
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: build and install wheel package
      run: |
        pip install wheel setuptools
        python setup.py sdist bdist_wheel
        find dist -name "*.whl" -type f -exec pip install {} \;
      shell: bash
